# Generated by Django 4.1.7 on 2023-03-08 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='theme_id',
            new_name='theme',
        ),
    ]
