# Generated by Django 4.1.7 on 2023-03-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0002_rename_theme_id_category_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='spreadsheetThemeCategory',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
