# Generated by Django 4.1.7 on 2023-03-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0003_transaction_spreadsheetthemecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
