# Generated by Django 4.1.7 on 2023-03-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0006_account_alter_category_name_alter_theme_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='labels',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
