# Generated by Django 4.1.7 on 2023-03-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0008_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
