# Generated by Django 4.1.7 on 2023-03-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0010_alter_transaction_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
