# Generated by Django 4.1.7 on 2023-08-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0011_alter_transaction_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='part_of_trip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trip_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
