# Generated by Django 4.1.7 on 2023-10-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0012_transaction_part_of_trip_transaction_trip_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='part_of_trip',
            new_name='part_of_travel_trip',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='trip_name',
            new_name='travel_trip_name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
