# Generated by Django 4.1.7 on 2023-10-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0013_rename_part_of_trip_transaction_part_of_travel_trip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='displayName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
