# Generated by Django 4.1.7 on 2023-10-24 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0014_account_displayname'),
    ]

    operations = [
        migrations.CreateModel(
            name='travelTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('totalSpent', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='travel_trip_name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='travel_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Budget.traveltrip'),
        ),
    ]
