# Generated by Django 4.1.7 on 2023-10-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0015_traveltrip_remove_transaction_travel_trip_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveltrip',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traveltrip',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
