# Generated by Django 4.1.7 on 2023-10-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0016_alter_traveltrip_enddate_alter_traveltrip_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveltrip',
            name='totalSpent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
